import asyncio
from typing import Protocol


class EmbeddingProvider(Protocol):
    model_name: str

    @property
    def is_ready(self) -> bool: ...

    def start_warmup(self) -> asyncio.Task[None]: ...

    async def warmup(self) -> None: ...

    async def dimension(self) -> int: ...

    async def embed_documents(self, texts: list[str]) -> list[list[float]]: ...

    async def embed_query(self, text: str) -> list[float]: ...

    async def aclose(self) -> None: ...
